services:
  web-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_NAME=$APP_NAME
        - WORK_DIR=$WORK_DIR
        - SOURCE_DIR=$SOURCE_DIR
    environment:
      - FLASK_APP=$ENTRY_PROGRAM
      - FLASK_ENV=$ENV
      - FLASK_DEBUG=1
      - LOG_DIR=$LOG_DIR
    ports:
      - 80:5000
    volumes:
      - ".:$WORK_DIR"
      - "~/.logs/bank_robbers:$LOG_DIR"
      - "~/.webapp_images/bank_robbers:$IMAGE_DIR"
    command: "bash $WORK_DIR/entrypoints/entrypoint.sh"
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/.mysql:/var/lib/mysql/
    ports:
      - 3306:3306
  # redis:
  #   image: "redis:alpine"
networks:
  default:
    name: xtaxi-dev-network
